---

  - name: install requirements
    become: yes
    apt: 
      name: "libio-socket-ssl-perl"

  - name: install logitech media service
    become: yes
    apt: 
      deb: "{{ logitech_media_service_download_url }}"
    notify: restart squeezeboxserver

  - name: add squeezeboxserver user to group for read/write access to share
    become: yes
    user:
      name: squeezeboxserver
      groups: "{{ music_server_group }}"
      append: yes
    notify: restart squeezeboxserver

  - name: make sure playlist folder exists with proper file permissions
    become: yes
    file:
      path: "{{ music_server_playlist_path }}"
      state: directory
      owner: squeezeboxserver
      group: "{{ music_server_group }}"
    notify: restart squeezeboxserver

  # Fix for spotty issue 41, downgrade to older version
  # https://github.com/michaelherger/Spotty-Plugin/issues/41
  #- name: downgrade spotty binary to older version as workaround for issue 41
  #  become: yes
  #  get_url:
  #    url:  "https://github.com/michaelherger/Spotty-Plugin/raw/8927261a6f536e76c8c1cf7d37923f2b4f1f454b/Bin/i386-linux/spotty-x86_64"
  #    dest: "/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/Spotty/Bin/i386-linux/spotty-x86_64"
  #    mode: "0755"
  #    owner: squeezeboxserver