---

  - name: install requirements
    become: yes
    apt: 
      name: "libio-socket-ssl-perl"

  - name: install logitech media service
    become: yes
    apt: 
      deb: "{{ lookup('url', '{{ logitech_media_service_download_url }}') }}"
    notify: restart squeezeboxserver

  - name: add squeezeboxserver user to group for read/write access to share
    become: yes
    user:
      name: squeezeboxserver
      groups: "{{ music_server_group }}"
      append: yes
    notify: restart squeezeboxserver

  - name: make sure playlist folder exists with proper file permissions
    become: yes
    file:
      path: "{{ music_server_playlist_path }}"
      state: directory
      owner: squeezeboxserver
      group: "{{ music_server_group }}"
    notify: restart squeezeboxserver