---

  - name: restart squeezeboxserver
    become: yes
    service: 
      name: logitechmediaserver
      state: restarted

  - name: restart nginx
    become: yes
    service: 
      name: nginx
      state: restarted
